server:
  port: 8082

spring:
  application:
    name: monitoring-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true